In [25]:
import torch 
from torch.autograd import Variable

In [26]:
a = Variable(torch.tensor([5., 4.]), requires_grad=True)
b = Variable(torch.tensor([6., 8.]))

y = a**3 + 5 * b        # forward pass: y = f(a, b)
print(y)

tensor([155., 104.], grad_fn=<AddBackward0>)


In [27]:
print(y.mean())

tensor(129.5000, grad_fn=<MeanBackward0>)


In [28]:
z = y.mean()      # grad can be implicitly created only for scalar outputs => need to convert y to scalar
z.backward()

# dz/da = 1/2 * 3*a^2 = a = [3/2 * 5.^2, 3/2 * 4.^2]
# dz/db = 1/2 * 5 * [1, 1] = [5/2, 5/2] if set gradient = True

print(a.grad)     # giá trị đạo hàm của hàm z theo biến a
print(b.grad)     # b has no gradient; 5/2 if set gradient equals True 

tensor([37.5000, 24.0000])
None


In [33]:
# Linear Regression
x = Variable(torch.randn(1, 10), requires_grad=False)    # observed values (deterministic) shape (1, 10)
W = Variable(torch.randn(10, 1), requires_grad=True)     # weight matrix                   shape (10, 1)
b = Variable(torch.randn(1), requires_grad=True)         # bias vector (set random)
y = Variable(torch.tensor([[0.822]]))

# x and y are fixed, need to find W and b through backpropagation

y_pred = torch.matmul(x, W) + b    # shape (1, 1)
print(y_pred)

loss = (y_pred - y).pow(2)
print(loss)

# Compute gradient
loss.backward()
print(W.grad)
print(b.grad)
print(b.grad.data)

lr = 0.001
# Update the weight matrix after backpropagation
with torch.no_grad():
    W = W - lr * W.grad.data
print(W)


tensor([[2.7089]], grad_fn=<AddBackward0>)
tensor([[3.5603]], grad_fn=<PowBackward0>)
tensor([[ 5.6172],
        [-0.8816],
        [ 4.2334],
        [-3.7615],
        [ 2.4110],
        [ 7.3217],
        [ 1.7600],
        [ 1.3792],
        [-0.6335],
        [ 3.9105]])
tensor([3.7737])
tensor([3.7737])
tensor([[ 1.1141],
        [-0.8696],
        [-0.0973],
        [ 0.3311],
        [-0.2771],
        [-0.0194],
        [ 0.2335],
        [-0.4242],
        [ 0.6443],
        [ 0.2801]])
