In [2]:
import torch

t = torch.ones(3, 4, 5)
print(t.size())
print(t.size(dim=0))
print(t.size(dim=1))

torch.Size([3, 4, 5])
3
4


In [3]:
max((5,))

5

In [4]:
x = torch.arange(1, 6)

print(x)
print(x.topk(3))                 # return 3 largest values (sorted) and their indices   => return namedtuple (values, indices)
print(x.topk(3).values)       
print(x.topk(3).indices)

tensor([1, 2, 3, 4, 5])
torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))
tensor([5, 4, 3])
tensor([4, 3, 2])


In [5]:
print(x.topk(3))               # latest dim is chosen if not specified
print(x.topk(3, 0))            # specify dim
print(x.topk(3, 0, True, True))   
print(x.topk(3, dim=0, largest=True, sorted=True))   # verbose mode for above 

torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))
torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))
torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))
torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))


In [6]:
# Input: (batch_size, channels, height, width) => (N, C, H, W)
# Ouput: (batch_size, score per class)

In [7]:
_, pred = x.topk(3, 0, True, True)      # first value is score, second value is class index
print(pred)

tensor([4, 3, 2])


In [26]:
x = torch.arange(20).reshape(2, 10)
print(x)

_, pred = x.topk(5, 1, True, True)    # top value on the 1 axis (per row)
print(pred)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[9, 8, 7, 6, 5],
        [9, 8, 7, 6, 5]])


In [27]:
pred.t()

tensor([[9, 9],
        [8, 8],
        [7, 7],
        [6, 6],
        [5, 5]])

In [28]:
target = torch.arange(2)
print(target)

target.view(1, -1)    # Expand 1D to 2D tensor with only one row

tensor([0, 1])


tensor([[0, 1]])

In [29]:
pred = pred.t()
target = target.view(1, -1).expand_as(pred)
print(target)

correct = pred.eq(target)      # compare values element-wise
print(correct)

tensor([[0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1]])
tensor([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]])


In [32]:
# The second way that does not require transpose
x = torch.arange(20).reshape(2, 10)
_, pred = x.topk(5, 1, True, True)    # top value on the 1 axis (per row)
print(pred)

target = torch.arange(2)
print(target)

target = target.view(2, -1).expand_as(pred)
print(target)

correct = pred.eq(target)
print(correct)

tensor([[9, 8, 7, 6, 5],
        [9, 8, 7, 6, 5]])
tensor([0, 1])
tensor([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [33]:
topk = (1, 2,)
for k in topk:
    print(k)

1
2


In [21]:
target = torch.arange(5).reshape(1, 5)  # 2D tensor
print(target)

target.view(-1)   # convert to 1D tensor

tensor([[0, 1, 2, 3, 4]])


tensor([0, 1, 2, 3, 4])

In [22]:
target.clone()

tensor([[0, 1, 2, 3, 4]])

In [74]:
topk = (1, 3, 5)
maxk = max(topk)

x = torch.arange(20).reshape(2, 10)
target = torch.arange(2)
batch_size = x.size(0)

_, pred = x.topk(maxk, 1, True, True)
pred = pred.t()
correct = pred.eq(target.view(1, -1).expand_as(pred))
print(correct)

res = []
for k in topk:
    correct_k = correct[:k].contiguous().view(-1).float().sum(0, keepdim=True)     # why need view(-1)???
    acc_k = correct_k.mul(100.0 / batch_size)
    print(acc_k)
    res.append(acc_k)

tensor([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]])
tensor([0.])
tensor([0.])
tensor([0.])


In [54]:
x = torch.arange(10).reshape(2, 5)
print(x)

print(x.sum())
print(x.sum(0))     # sum each column
print(x.sum(1))     # sum each row 
print(x.sum(0, keepdim=True))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor(45)
tensor([ 5,  7,  9, 11, 13])
tensor([10, 35])
tensor([[ 5,  7,  9, 11, 13]])


In [57]:
x = torch.arange(10).reshape(2, 5)
print(x)

x = x.view(-1)     # flatten the tensor 
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [67]:
x = torch.tensor([[False, True], 
                  [True, False], 
                  [False, True]])

print(x)
print(x.view(-1))

tensor([[False,  True],
        [ True, False],
        [False,  True]])
tensor([False,  True,  True, False, False,  True])


In [68]:
print(x[:2])
print(x[:2].view(-1))

tensor([[False,  True],
        [ True, False]])
tensor([False,  True,  True, False])


In [78]:
x = torch.arange(12).reshape(3, 4)   
print(x)

print(x.narrow(dim=0, start=0, length=2))     # a narrow / truncated version of x along column dimension
print(x.narrow(dim=1, start=0, length=2))     # 

# Nhận xét: narrow giống slicing nhưng khác ở chỗ là nó chỉ truncate theo một chiều thôi 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1],
        [4, 5],
        [8, 9]])


In [79]:
x.narrow(1, 1, 2)

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [80]:
x = torch.tensor([1.0])    # (only work for 1-element tensor) return a 1-element tensor to standard Python number
x.item()

1.0